- hosts: museum
  gather_facts: no
  become: True

  vars:
    ansible_python_interpreter: /usr/bin/python3
    gunicorn_port: 8000
    db_user: "teacher"
    db_name: "museum"
    db_pass: " "
    projdir: " "
    wsgi_folder: "museum"
    secret_key: ##############
    sql_host: "localhost"
    sql_port: "5432"
    site_owner: "webprog"
    etcdir: " " #сюда положится конфиг  Гуникорна
    gunicorn_port: 8000
    django_allowed_hosts: "####### localhost"
    debug: 0
    repositary: #####

  roles:
    # - role: 'deploy/django-demo-app/nginx'
    #   tags: ['nginx']
   
    # - role: 'deploy/django-demo-app/db'
    #   tags: ['db']

    # - role: 'deploy/django-demo-app/app'
    #   tags: ['app']

    - role: 'deploy/django-demo-app/gunicorn'
      tags: ['gunicorn']


  